services:
  # 1. 数据库服务
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: factory_es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - factory-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: factory_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - factory-net

  # 2. 后端服务
  backend:
    image: factory_agent-backend:latest
    container_name: factory_backend
    ports:
      - "8000:8000"
    volumes:
      # 挂载数据目录，确保上传的文件和图片持久化
      - ./factory_docs:/app/factory_docs
      - ./factory_images:/app/factory_images
      - ./unanswered_questions.json:/app/unanswered_questions.json
      # 挂载模型目录
      - ./models:/app/models
    environment:
      - HF_HOME=/app/models
      - SENTENCE_TRANSFORMERS_HOME=/app/models
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - DASHSCOPE_API_KEY=${DASHSCOPE_API_KEY} # 从 .env 文件读取 Key
    depends_on:
      - elasticsearch
    networks:
      - factory-net

  # 3. 前端服务
  frontend:
    image: factory_agent-frontend:latest
    container_name: factory_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - factory-net

volumes:
  es_data:


networks:
  factory-net:
    driver: bridge
